"""Conformance tests for the SoftwareX article's illustrative examples.

Every number quoted in Section 3.2 of the manuscript (pump diagnosis, free and
hybrid DSm models) is pinned here, so any library change that would silently
invalidate the paper fails CI.  The values are generated by
``examples/example_3_pump_hybrid.py``.
"""

from __future__ import annotations

from pytest import approx

from evidencelib import Frame


def _pump_sources(frame):
    e, m, h = frame.symbols()
    current = frame.mass({e: 0.65, e | m: 0.20, e | m | h: 0.15})
    vibration = frame.mass({m: 0.60, e | m: 0.25, e | m | h: 0.15})
    pressure = frame.mass({h: 0.25, e | h: 0.15, m | h: 0.10, e | m | h: 0.50})
    return current, vibration, pressure


def test_pump_free_model_dsmc_masses_from_section_3_2() -> None:
    frame = Frame.dsmt(["E", "M", "H"])
    e, m, h = frame.symbols()
    current, vibration, pressure = _pump_sources(frame)

    assert len(frame.elements()) == 19

    result = current.dsmc(vibration, pressure)

    assert result[e & m] == approx(0.2925)
    assert result[e & m & h] == approx(0.0975)
    assert result[e & h] == approx(0.0650)
    assert result[frame.empty] == approx(0.0)
    assert result.total_mass == approx(1.0)


def test_pump_free_model_pignistic_regions_from_section_3_2() -> None:
    frame = Frame.dsmt(["E", "M", "H"])
    current, vibration, pressure = _pump_sources(frame)

    regions = current.dsmc(vibration, pressure).pignistic_regions()

    assert regions["E&M&H"] == approx(0.425, abs=5e-4)
    assert regions["E&M"] == approx(0.257, abs=5e-4)
    assert sum(regions.values()) == approx(1.0)


def test_pump_hybrid_model_dsmh_masses_from_section_3_2() -> None:
    free = Frame.dsmt(["E", "M", "H"])
    current, vibration, pressure = _pump_sources(free)
    hybrid = Frame.hybrid(["E", "M", "H"], empty=["E&H"])
    e, m, h = hybrid.symbols()

    assert len(hybrid.elements()) == 13
    assert not e & h
    assert not e & m & h

    result = current.dsmh(vibration, pressure, model=hybrid)

    expected = {
        e & m: 0.3185,
        e: 0.169,
        m: 0.13775,
        m & h: 0.081875,
        (e & m) | (m & h): 0.0315,
        e | (m & h): 0.017625,
        e | m: 0.05875,
        e | h: 0.003375,
        m | h: 0.00225,
        h: 0.005625,
        e | m | h: 0.17375,
    }
    assert set(result.focal()) == set(expected)
    for proposition, value in expected.items():
        assert result[proposition] == approx(value)
    assert result.total_mass == approx(1.0)


def test_pump_deng_entropy_before_and_after_the_hybrid_constraint() -> None:
    free = Frame.dsmt(["E", "M", "H"])
    current, vibration, pressure = _pump_sources(free)
    hybrid = Frame.hybrid(["E", "M", "H"], empty=["E&H"])

    free_result = current.dsmc(vibration, pressure)
    hybrid_result = current.dsmh(vibration, pressure, model=hybrid)

    assert free_result.deng_entropy() == approx(5.8371, abs=5e-5)
    assert hybrid_result.deng_entropy() == approx(4.5523, abs=5e-5)


def test_pump_hybrid_model_pignistic_regions_from_section_3_2() -> None:
    free = Frame.dsmt(["E", "M", "H"])
    current, vibration, pressure = _pump_sources(free)
    hybrid = Frame.hybrid(["E", "M", "H"], empty=["E&H"])

    result = current.dsmh(vibration, pressure, model=hybrid)
    regions = result.pignistic_regions()

    assert set(regions) == {"E", "M", "H", "E&M", "M&H"}
    assert regions["E&M"] == approx(0.521, abs=5e-4)
    assert regions["M&H"] == approx(0.203, abs=5e-4)
    assert regions["E"] == approx(0.1407, abs=5e-4)
    assert regions["M"] == approx(0.0959, abs=5e-4)
    assert regions["H"] == approx(0.0390, abs=5e-4)
    assert sum(regions.values()) == approx(1.0)
